# Generated by Django 4.2.3 on 2024-05-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='fooditems',
            new_name='fooditem',
        ),
    ]
