# Generated by Django 4.2.3 on 2024-05-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_location_userprofile_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='modeified_date',
            new_name='modified_date',
        ),
    ]
