# Generated by Django 4.2.3 on 2024-05-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_modeified_date_user_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='locations',
        ),
    ]
