# Generated by Django 4.2.3 on 2024-05-05 05:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locations',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
