# Generated by Django 4.2.3 on 2023-08-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avalaible',
            new_name='is_available',
        ),
    ]
